#include <stdio.h>
#include <string.h>
#include <stdint.h>
#define MAGIC_STATE 0x6D47
static uint16_t rol16(uint16_t x,unsigned r){return (uint16_t)((x<<r)|(x>>(16-r)));}
static uint16_t update_state(uint16_t s,const char*c){if(!strcmp(c,"ping"))s^=0x13;else if(!strcmp(c,"sync")){s=rol16(s,3);s^=0x2B;}else if(!strcmp(c,"trace")){s^=0xA7;s=(uint16_t)(s+0x29);}else if(!strcmp(c,"status"))s=(uint16_t)(s*5+0x11);else if(!strcmp(c,"recover")){s^=0xD1;s=rol16(s,5);}else if(!strcmp(c,"purge"))s^=0xFFFF;return s;}
static const unsigned char blob[]={ 0x4F,0x5C,0x70,0x70,0x96,0x97,0x76,0x7B,0x43,0x0A,0xFC,0x71,0x4B,0x53,0x40,0xF1,0xA4,0x3C,0x78,0x1A,0x55,0x97,0x71,0x7D,0x44,0x01,0xAC,0xBB,0x38,0x7E,0x54 };
static void recover(uint16_t s){char out[64];size_t n=sizeof(blob);for(size_t i=0;i<n;i++){unsigned char m=(unsigned char)(0x41+(i*17)%0x5D);m^=(unsigned char)(s&0xff);out[i]=(char)(blob[i]^m);}out[n]=0;puts("\n==============================================================");puts("                     GHOST PROTOCOL");puts("==============================================================");puts("\n[+] Protocol state accepted.");puts("[!] Residual memory detected.");puts("[!] Source integrity: 17%");puts("\nRecovering deleted fragment...");puts("\n> \"They told us the process was dead.\"");puts("\n> \"It wasn't.\"");printf("\n[+] Fragment recovered.\n\nFLAG:\n%s\n",out);puts("\n==============================================================");puts("                     Created by AribZobair");puts("==============================================================");}
int main(void){char c[64];uint16_t s=0;puts("==============================================================");puts("                    RECOVERED TERMINAL");puts("                         CASE 17");puts("==============================================================");puts("\nThe machine was recovered from a sealed laboratory.");puts("Most research data has been destroyed.");puts("\nIDENT: GHOST");puts("\nAvailable commands: ping status reset auth sync");puts("\nGHOST PROTOCOL: INACTIVE");for(;;){printf("\nghost> ");fflush(stdout);if(!fgets(c,sizeof(c),stdin))break;c[strcspn(c,"\n")]=0;if(!strcmp(c,"help")){puts("\nAvailable commands: ping status reset auth sync");puts("[!] Some legacy commands may still exist.");continue;}if(!strcmp(c,"reset")){s=0;puts("\n[+] Protocol state reset.");continue;}if(!strcmp(c,"auth")){puts("\n[-] Authentication subsystem unavailable.");continue;}if(!strcmp(c,"ping")){s=update_state(s,c);puts("\n[+] PONG");}else if(!strcmp(c,"status")){s=update_state(s,c);puts("\n[+] SYSTEM STATUS: NOMINAL");}else if(!strcmp(c,"sync")){s=update_state(s,c);puts("\n[+] Synchronization channel opened.");}else if(!strcmp(c,"trace")){s=update_state(s,c);puts("\n[+] Trace subsystem responding.");}else if(!strcmp(c,"recover")){s=update_state(s,c);puts("\n[+] Recovery routine invoked.");}else if(!strcmp(c,"purge")){s=update_state(s,c);puts("\n[+] Purge request accepted.");}else puts("\n[-] Unknown command.");if(s==MAGIC_STATE){recover(s);return 0;}}return 0;}
